---

- name: create the Obj folder if it does not exist
  file:
    path: ../processFiles/6-RotatedSTLFrames
    state: directory

- name: create the STL folder if it does not exist
  file:
    path: ../processFiles/7-rotatedOBJ
    state: directory

- name: find each .obj file to import
  find:
    paths: ../processFiles/6-RotatedSTLFrames
    patterns: "*.stl"
    recurse: yes
  register: stlFiles

- name: import the OBJ files
  become: yes
  command: "'/mnt/c/Program Files/Blender Foundation/Blender 3.2/blender.exe'  -b -P /roles/5.1ConvertBackToOBJ/files/convertBackToOBJ.py -- {{ item.0.path }} {{ item.1 }}"
  register: result
  retries: 3
  until: "result is not failed"
  with_nested:
    - "{{ stlFiles.files }}"
    - "{{ overlayShapes }}"

- name: find each .mtl file which we won't need
  find:
    paths: ../processFiles/7-rotatedOBJ
    patterns: "*.mtl"
    recurse: yes
  register: mtlFiles

- name: remove the .mtl files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ mtlFiles.files }}"

#- name: Shows
#  debug:
#    var: result
