---

- name: create the OBJ folder if it does not exist
  file:
    path: ../processFiles/7-rotatedOBJ
    state: directory

- name: find each directory containing stl files
  find:
    paths: ../processFiles/6-RotatedSTLFrames
    file_type: directory
  register: STLFiles

- name: Show file paths basename
  debug:
    msg: "{{ item.path | basename }}"
  with_items: "{{ STLFiles.files }}"

- name: create the OBJ subdir if it does not exist
  file:
    path: ../processFiles/7-rotatedOBJ/{{ item.path | basename }}
    state: directory
  with_items: "{{ STLFiles.files }}"

#- name: Convert the stl back to an obj
#  become: yes
#  command: "'/mnt/c/Program Files/Blender Foundation/Blender 3.2/blender.exe'  -b -P /roles/5.1ConvertBackToOBJ/files/convertBackToObj.py -- {{ item.path | basename }}"
#  with_items: "{{ STLFiles.files }}"
#  register: result

- name: Convert the stl back to a flipped obj, a nonflipped obj then combine the two
  become: yes
  command: "'/mnt/c/Program Files/Blender Foundation/Blender 3.2/blender.exe'  -b -P /roles/5.1ConvertBackToOBJ/files/convertBackToObjDoubleSided.py -- {{ item.path | basename }}"
  with_items: "{{ STLFiles.files }}"
  register: result

- name: find each .mtl file which we won't need
  find:
    paths: ../processFiles/7-rotatedOBJ
    patterns: "*.mtl"
    recurse: yes
  register: mtlFiles

- name: remove the .mtl files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ mtlFiles.files }}"

- name: Show output from the python script
  debug:
    var: result