
## Command to make the file run ##
#
# sudo '../../../mnt/c/Program Files/Blender Foundation/Blender 3.2/blender.exe'  -b -P importscript.py -- 1 1
#
## ARGV ##
#ARGV[0] - Convert fbx files into obj files for each frame 1=YES 0=NO
#ARGV[1] - Convert obj files into STL files 1=YES 0=NO
#

# Import the needed modules (bpy is Blender)

import bpy
import math
import os
import re
import sys


#
## Values that could change ##
# Animation speed (how far apart frames are)
animSpeed=1
# save/load .obj files to/from
finalObjDirectory = '../processFiles/7-rotatedOBJ'
# load .stl files from
stlDirectory = '../processFiles/6-RotatedSTLFrames'


# Get the arguments and save as strings
argv = sys.argv
argv = argv[argv.index("--") + 1:]  # get all args after "--"
##print(argv)

# delete starting objects generated by Blender by Default
#print("Deleting Starting Objects")
#print("")
startingObjects = ["Light", "Camera"]
for obj in startingObjects:
    bpy.data.objects[obj].select_set(True)    
    bpy.context.view_layer.objects.active = bpy.data.objects[obj]
bpy.ops.object.delete()


######## Import final STLs ##########


# For each subdirectory with obj frames, then for each frame import it back in
subdir=os.path.join(stlDirectory, argv[0])
for filename in os.listdir(subdir):
    if re.search("stl", filename):
        f = os.path.join(subdir, filename)
        # checking if it is a file
        if os.path.isfile(f):
            print("FOUND STL\n\n\n")
            print(f)
            bpy.ops.import_mesh.stl(filepath=f)
            objects = bpy.context.scene.objects
            

            scene = bpy.context.scene
            selected = bpy.context.selected_objects
            meshes = [o for o in selected if o.type == 'MESH']

            for obj in meshes:
                print("MESHYSHUSGIG")
#                scn.objects.active = obj
                bpy.ops.object.editmode_toggle()
                bpy.ops.mesh.select_all(action='SELECT')
                bpy.ops.mesh.flip_normals() # just flip normals

            bpy.ops.object.mode_set(mode='OBJECT')
            bpy.ops.object.select_all(action='SELECT')
            bpy.ops.export_scene.obj(filepath=finalObjDirectory+"/"+argv[0]+"/Flipp"+filename[:-3]+"obj",use_selection=True)
            bpy.ops.object.delete()
            for obj in objects:
                print(obj.name)