---

- name: create the FBX folder if it does not exist
  file:
    path: ../processFiles/1-originalFBX
    state: directory

- name: create the Obj folder if it does not exist
  file:
    path: ../processFiles/2-FBXintoOBJ
    state: directory

- name: import the FBX files
  become: yes
  command: "'/mnt/c/Program Files/Blender Foundation/Blender 3.2/blender.exe'  -b -P /roles/1.1ConvertFBXtoOBJ/files/convertFBXtoOBJ.py -- {{ item }}"
  register: result
  with_fileglob:
    - ../processFiles/1-originalFBX/*

- name: show
  debug:
    var: result

- name: find each .mtl file which we won't need
  find:
    paths: ../processFiles/2-FBXintoOBJ
    patterns: "*.mtl"
    recurse: yes
  register: result

- name: remove the .mtl files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"
  