---

- name: create the ProcessFiles folder if it does not exist
  file:
    path: ../processFiles
    state: directory

- name: create the FBX folder if it does not exist
  file:
    path: ../processFiles/1-originalFBX
    state: directory

- name: move the fbx files from the seeding area into the FBX folder
  copy:
    src: "{{ item }}"
    dest: ../processFiles/1-originalFBX
  with_fileglob:
    - ../seedingArea/fbx/*